import { createSlice } from "@reduxjs/toolkit";

// Creating a slice for the cart functionality
// This slice will manage the state of items in the cart, including adding, incrementing, and decrementing items
const cart = createSlice({
	// Name of the slice — will be used as a key in the Redux state
	name: "cartSlicer",

	// Initial state of the slice
	// items: An array to hold the items in the cart
	// itemCount: A counter to keep track of the total number of items in the cart
	initialState: {
		items: [],
		itemCount: 0,
	},

	// Reducers — functions to update the state based on dispatched actions
	reducers: {
		// Adds a new item to the cart
		addItem: (state, action) => {
			// Push the new item into the cart array with a default quantity of 1
			state.items.push({ ...action.payload, quantity: 1 });

			// Increment the item count in the cart
			// This is necessary to keep track of how many items are in the cart
			state.itemCount++;
		},

		// Increments the quantity of a specific item
		incrementItem: (state, action) => {
			// Find the item in the cart by its ID
			// If the item exists, increment its quantity
			const item = state.items.find((item) => item.id === action.payload.id);

			// Increase its quantity
			item.quantity += 1;

			// Increase total item count
			state.itemCount++;
		},

		// Decrements the quantity of a specific item
		decrementItem: (state, action) => {
			// Find the item in the cart by its id
			const item = state.items.find((item) => item.id === action.payload.id);

			if (item.quantity > 1) {
				// If quantity > 1, decrease it
				item.quantity -= 1;
			} else {
				// If quantity is 1, remove the item from the cart
				state.items = state.items.filter(
					(item) => item.id !== action.payload.id
				);
			}

			// Decrease the total item count
			state.itemCount--;
		},
	},
});

// Exporting the actions generated by createSlice
export const { addItem, incrementItem, decrementItem } = cart.actions;

// Exporting the reducer function to be used in the store
export default cart.reducer;
